#ifndef PLEX_DEFAULTLIMITS_H
#define PLEX_DEFAULTLIMITS_H

#define PLEX_DEFMIN_WIDTH 800
#define PLEX_DEFMAX_WIDTH 4096
#define PLEX_DEFAULT_WIDTH 800

#define PLEX_DEFMIN_HEIGHT 600
#define PLEX_DEFMAX_HEIGHT 2160
#define PLEX_DEFAULT_HEIGHT 600

#define PLEX_DEFAULT_CURSORR 255
#define PLEX_DEFAULT_CURSORG 255
#define PLEX_DEFAULT_CURSORB 255

#endif
